language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -Dmaven.javadoc.skip=false -B -V
  - ./mvnw clean test -B -V

after_deploy:
  - ./mvnw docker:build
